# Generated by Django 4.2.2 on 2023-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=13)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('gender', models.CharField(max_length=3)),
                ('appointment_date', models.CharField(max_length=100, verbose_name='appointment date')),
                ('scheduled_time', models.CharField(max_length=100, verbose_name='scheduled time')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
